import os
sources=[
	"aaac.cpp",
	"aarj.cpp",
	"aarq.cpp",
	"AssociationRejection.cpp",
	"Buffer.cpp",
	"Cdimse.cpp",
	"ClientConnection.cpp",
	"CommandSets.cpp",
	"DataDictionary.cpp",
	"Decoder.cpp",
	"Dumper.cpp",
	"Encoder.cpp",
	"Exceptions.cpp",
	"File.cpp",
	"FileMetaInformation.cpp",
	"GroupLength.cpp",
	"Ndimse.cpp",
	"pdata.cpp",
	"PresentationContexts.cpp",
	"QueryRetrieve.cpp",
	"Server.cpp",
	"ServiceBase.cpp",
	"Tag.cpp",
	"ThreadSpecificServer.cpp",
	"TransferSyntax.cpp",
	"UID.cpp",
	"Utility.cpp",
	"ValueToStream.cpp",
	"Version.cpp"]


cpppath=['..']

env = Environment(CPPPATH=cpppath)

env.StaticLibrary(target = 'dicom', source = sources)

# We could also make a shared libray as follows:
# env.SharedLibrary(target = 'dicom', source = sources)

